name: "Lint and Test Charts"

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
  workflow_dispatch:
    inputs:
      lint-n-test:
        type: boolean
        default: false
        required: false
        description: Run lint and test charts

permissions:
  contents: read

jobs:
  lint-test:
    name: "Lint and Test Helm Charts"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: "Set up Helm"
        uses: azure/setup-helm@v4.3.1
        with:
          version: v3.17.0

      - name: "Set up Python"
        uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c # v6.0.0
        with:
          python-version: '3.x'
          check-latest: true

      - name: "Set up chart-testing"
        uses: helm/chart-testing-action@v2.8.0

      - name: "Run chart-testing (list-changed)"
        id: list-changed
        run: |
          changed=$(ct list-changed --target-branch ${{ github.event.repository.default_branch }})
          if [[ -n "$changed" ]]; then
            echo "changed=true" >> "$GITHUB_OUTPUT"
          fi

      - name: "Run chart-testing (lint)"
        if: steps.list-changed.outputs.changed == 'true' || inputs.lint-n-test == true
        run: ct lint --target-branch ${{ github.event.repository.default_branch }}

      - name: "Create kind cluster"
        if: steps.list-changed.outputs.changed == 'true' || inputs.lint-n-test == true
        uses: helm/kind-action@v1.13.0

      - name: "Run chart-testing (install)"
        if: steps.list-changed.outputs.changed == 'true' || inputs.lint-n-test == true
        run: ct install --target-branch ${{ github.event.repository.default_branch }}
